### ISSUE TITLE
seleniumを起動させてcolabを操作する

### ISSUE THREAD

**Issue by yonedahayato** [yonedahayato/google#6]
# タスク
- [x] localでcolabを起動し、その起動を確認する
- [ ] docker 環境で起動し、その起動を確認する
- [ ] サーバをたてて、colab を起動し、その起動を確認する

## docker 環境で起動し、その起動を確認する
- [ ] docker を使用する
  - [x] Dockerfile 作成
  - [x] docker_exe.sh 作成
  - docker からのcolabへのアクセス時にエラーが発生する(エラー05参照)

# 使用サーバ
- サーバ名 : colab-test-env
  - 使用中止(2019/10/23)

## 参考
- [ヘッドレスCHROMEの起動設定方法](https://gogogodai.com/headless-chrome/)

**Comment by yonedahayato** [comment]
# エラー
## 2019/10/07
- [ヘッドレスCHROMEの起動設定方法](https://gogogodai.com/headless-chrome/)

**Comment by yonedahayato** [comment]
# エラー
## 2019/10/11
```
Traceback (most recent call last):
  File "exec_gcolab.py", line 13, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by yonedahayato** [comment]
# エラー05
## 2019/10/24
![screenshot_2019-10-14-07-23-55](https://user-images.githubusercontent.com/19747958/67446726-815fd700-f64c-11e9-941d-88bd6f57677c.png)

**Comment by yonedahayato** [comment]
# 2019/11/17
docker 環境で seleniumを使用して google colab を使用することが難しそうなので、APIを作成して(lambda や cloud function等の serverless のサービスを使用?)を外部からgoogle colabを起動させる
